#!/bin/bash

apt-get install python3
apt-get install python3-pip
apt-get install redis-server

pip3 install redis
pip3 install psycopg2 

chmod +x install
chmod +x door_cli.py
chmod +x door_control/door_controller.py

cp door_cli.py /usr/bin/door
chmod +x /usr/bin/door

mkdir -p /usr/etc/door

cp door_control/door_controller.py /usr/bin
cp door_control/door_controller.service /etc/systemd/system

systemctl start door_controller
