#!/bin/bash

apt-get install python3
apt-get install python3-pip
apt-get install redis-server

pip3 install redis
pip3 install psycopg2 
pip3 install python-logging-loki

chmod +x install
chmod +x door_cli.py
chmod +x door_control/door_controller.py
chmod +x access_control/access_control.py

cp door_cli.py /usr/bin/door
chmod +x /usr/bin/door

mkdir -p /usr/etc/door

cp door_control/door_controller.py /usr/bin
cp access_control/access_control.py /usr/bin

cp door_control/door_controller.service /etc/systemd/system
cp access_control/access_control.service /etc/systemd/system

systemctl start door_controller
systemctl start access_control

systemctl restart door_controller
systemctl restart access_control

systemctl daemon-reload
